export const general = {
    logo: "images/generated/foosheekalogo.png",
    name: "Mehdi Ben Ayed",
    address: "Budapest, Hungary",
    intro: "punchline, paragraph",
    facebook: "https://www.facebook.com/happy.mahdi/",
    linkedin: "https://www.linkedin.com/in/ben-ayed-mehdi/",
    youtube: "https://www.youtube.com/channel/UCcJRMal-mHtTVnuU33jv9-Q",
    github: "https://github.com/BenAyedMehdi",
    email: "mr.mehdi.ben.ayed@gmail.com",
    phone: "(+36) 20 483 4845",
    website: "mehdibenayed.netlify.app",
    punchline: "I help you create the solution that you have in mind",

    images: {
      img1: "mehdi_images/standing.jpg",
      img2: "mehdi_images/speach.jpg",
      img3: "mehdi_images/mentor.jpg",
      img4: "mehdi_images/junctionxteam.jpg",
      img5: "mehdi_images/landing_img.jpg",
      img6: "mehdi_images/22.jfif",
      img7: "mehdi_images/speech.jpg",
      img8: "mehdi_images/graduationsuccess.jpg",
    },
  };
